version: '3.0'
services:
  activepieces:
    image: ghcr.io/activepieces/activepieces:0.45.1
    container_name: activepieces
    restart: unless-stopped
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    ports:
      - '8080:80'
    depends_on:
      - postgres
      - redis
    environment:
      - 'AP_CONTAINER_TYPE=APP'
    env_file: .env
    volumes:
      - ./cache:/usr/src/app/cache
    networks:
      - activepieces_2
  worker_1:
    image: ghcr.io/activepieces/activepieces:0.46.5
    container_name: worker_1
    restart: unless-stopped
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - 'AP_WORKER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJpZCI6InFiZFlWcHY3ZzZISHRIRlVGZVA2VyIsInR5cGUiOiJXT1JLRVIiLCJpYXQiOjE3NDEzNTY2MjQsImV4cCI6NDg5NDk1NjYyNCwiaXNzIjoiYWN0aXZlcGllY2VzIn0.oAXynFjOLS_upB0Ll03550dq-387MbyCG8TdgB1WLPE'
      - 'AP_CONTAINER_TYPE=WORKER'
      - 'AP_FRONTEND_URL=http://activepieces'
    volumes:
      - ./cache2:/usr/src/app/cache
    networks:
      - activepieces_2
  worker_2:
    image: ghcr.io/activepieces/activepieces:0.46.5
    container_name: worker_2
    restart: unless-stopped
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - 'AP_WORKER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJpZCI6IjJ1VlljWUlkZmg5cjdYTURUN2FVTyIsInR5cGUiOiJXT1JLRVIiLCJpYXQiOjE3NDEzNTY5NjksImV4cCI6NDg5NDk1Njk2OSwiaXNzIjoiYWN0aXZlcGllY2VzIn0.fBQ7j3DudUoqZcgD6XGAgPkCklzdmtGNzLca7rZpC_4'
      - 'AP_CONTAINER_TYPE=WORKER'
      - 'AP_FRONTEND_URL=http://activepieces'
    volumes:
      - ./cache3:/usr/src/app/cache
    networks:
      - activepieces_2
  worker_3:
    image: ghcr.io/activepieces/activepieces:0.46.5
    container_name: worker_3
    restart: unless-stopped
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - 'AP_WORKER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEifQ.eyJpZCI6IndyU1I1b1RtS3VtdWxEVVR2RTdFaSIsInR5cGUiOiJXT1JLRVIiLCJpYXQiOjE3NDEzNTc1ODAsImV4cCI6NDg5NDk1NzU4MCwiaXNzIjoiYWN0aXZlcGllY2VzIn0.3AD2EG5RzhZKd1eUfkFmJSxOMcdE6q292psi-KM7ap8'
      - 'AP_CONTAINER_TYPE=WORKER'
      - 'AP_FRONTEND_URL=http://activepieces'
    volumes:
      - ./cache4:/usr/src/app/cache
    networks:
      - activepieces_2
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME}'
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
    networks:
      - activepieces_2
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - 'redis_data_2:/data'
    networks:
      - activepieces_2
volumes:
  postgres_data_2:
  redis_data_2:
networks:
  activepieces_2:
